;---------------------------------------------------------------
; EEPROM Configuration
;---------------------------------------------------------------

	EXTERN configAPRSSymbolTableNormal
	EXTERN configAPRSSymbolNormal
	EXTERN configMicEMessageNormal
	EXTERN configStatusTextNormal

	EXTERN configAPRSSymbolTableAlternate
	EXTERN configAPRSSymbolAlternate
	EXTERN configMicEMessageAlternate
	EXTERN configStatusTextAlternate

	EXTERN configAPRSSymbolTableEmergency
	EXTERN configAPRSSymbolEmergency
	EXTERN configMicEMessageEmergency
	EXTERN configStatusTextEmergency

	EXTERN configVersionText
	
	EXTERN configMyCallsign
	EXTERN configDestSSID