;------------------------------------------------------------------------------
; This file was auto-generated by PICStateGenerator. Do not edit.
;------------------------------------------------------------------------------
              list     p=18F14K50
#include "p18f14k50.inc"

              GLOBAL   gpsInit
              GLOBAL   gpsStep
              GLOBAL   gpsLatitudeDegMin
              GLOBAL   gpsFlags
              GLOBAL   gpsLongitudeHundredths
              GLOBAL   gpsTime
              GLOBAL   gpsLongitudeDegMin
              GLOBAL   gpsQuality
              GLOBAL   gpsLatitudeHundredths
              GLOBAL   gpsInput

gpsAcs        UDATA_ACS
_statePtr              res .2
gpsFlags               res .1
gps_storeCount         res .1
gpsInput               res .1

              ; Please set up the linker to locate this block as required.
gpsBank1      UDATA
gpsLatitudeDegMin      res .4
gpsLongitudeHundredths   res .2
gpsTime                res .6
gpsLongitudeDegMin     res .5
gpsQuality             res .1
gpsLatitudeHundredths   res .2

gpsCode       CODE

;------------------------------------------------------------------------------
; State model initialisation.
;------------------------------------------------------------------------------
gpsInit:      MOVLW    HIGH(step_root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; State model entry point.
; This method executes the code for the current state.
;------------------------------------------------------------------------------
gpsStep:      CLRF     PCLATU, A
              MOVFF    (_statePtr + .1), PCLATH
              MOVF     _statePtr, W, A
              MOVWF    PCL, A

;------------------------------------------------------------------------------
; Node root entry code.
;------------------------------------------------------------------------------
              ;  Transition GOTO root
enter_root:   MOVLW    HIGH(step_root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node root step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_root:
              ;  Precondition gpsInput == '$'
trans0:       MOVLW    .36
              CPFSEQ   gpsInput, A
              GOTO     trans1
              ;  Transition GOTO (Shared) dollar
              GOTO     enter_dollar
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans1:       GOTO     enter_root

;------------------------------------------------------------------------------
; Node dollar entry code.
;------------------------------------------------------------------------------
              ;  Transition GOTO dollar
enter_dollar: MOVLW    HIGH(step_dollar)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_dollar)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node dollar step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_dollar:
              ;  Precondition gpsInput == 'G'
trans2:       MOVLW    .71
              CPFSEQ   gpsInput, A
              GOTO     trans3
              ;  Transition GOTO gps_State_0000
              MOVLW    HIGH(step_gps_State_0000)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0000)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans3:       GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0000 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0000:
              ;  Precondition gpsInput == 'P'
trans4:       MOVLW    .80
              CPFSEQ   gpsInput, A
              GOTO     trans5
              ;  Transition GOTO gps_State_0001
              MOVLW    HIGH(step_gps_State_0001)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0001)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans5:       GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0001 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0001:
              ;  Precondition gpsInput == 'G'
trans6:       MOVLW    .71
              CPFSEQ   gpsInput, A
              GOTO     trans7
              ;  Transition GOTO gps_State_0002
              MOVLW    HIGH(step_gps_State_0002)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0002)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans7:       GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0002 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0002:
              ;  Precondition gpsInput == 'G'
trans8:       MOVLW    .71
              CPFSEQ   gpsInput, A
              GOTO     trans9
              ;  Transition GOTO gps_State_0003
              MOVLW    HIGH(step_gps_State_0003)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0003)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans9:       GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0003 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0003:
              ;  Precondition gpsInput == 'A'
trans10:      MOVLW    .65
              CPFSEQ   gpsInput, A
              GOTO     trans11
              ;  Precondition Flag gpsFlags:0 == false
              BTFSC    gpsFlags, 0, A
              GOTO     trans11
              ;  Transition GOTO gps_State_0004
              MOVLW    HIGH(step_gps_State_0004)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0004)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans11:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0004 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0004:
              ;  Precondition gpsInput == ','
trans12:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans13
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsTime := 0
              BANKSEL  gpsTime
              CLRF     gpsTime
              CLRF     (gpsTime + .1)
              CLRF     (gpsTime + .2)
              CLRF     (gpsTime + .3)
              CLRF     (gpsTime + .4)
              CLRF     (gpsTime + .5)
              ;  Transition GOTO gps_State_0005
              MOVLW    HIGH(step_gps_State_0005)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0005)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans13:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0005 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0005:
              ;  Precondition gpsInput >= '0'
trans14:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans15
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans15
              ;  Precondition gps_storeCount <= 0x04
              MOVLW    .5
              CPFSLT   gps_storeCount, A
              GOTO     trans15
              ;  Command gpsTime[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsTime
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO SELF
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= '0'
trans15:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans16
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans16
              ;  Precondition gps_storeCount == 0x05
              MOVLW    .5
              CPFSEQ   gps_storeCount, A
              GOTO     trans16
              ;  Command gpsTime[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsTime
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0006
              MOVLW    HIGH(step_gps_State_0006)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0006)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans16:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0006 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0006:
              ;  Precondition gpsInput == '$'
trans17:      MOVLW    .36
              CPFSEQ   gpsInput, A
              GOTO     trans18
              ;  Transition GOTO (Shared) dollar
              GOTO     enter_dollar
              ; -- Start of transition --
              ;  Precondition gpsInput == ','
trans18:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans19
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsLatitudeDegMin := 0
              BANKSEL  gpsLatitudeDegMin
              CLRF     gpsLatitudeDegMin
              CLRF     (gpsLatitudeDegMin + .1)
              CLRF     (gpsLatitudeDegMin + .2)
              CLRF     (gpsLatitudeDegMin + .3)
              ;  Transition GOTO gps_State_0007
              MOVLW    HIGH(step_gps_State_0007)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0007)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO SELF
trans19:      RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0007 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0007:
              ;  Precondition gpsInput >= '0'
trans20:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans21
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans21
              ;  Precondition gps_storeCount <= 0x02
              MOVLW    .3
              CPFSLT   gps_storeCount, A
              GOTO     trans21
              ;  Command gpsLatitudeDegMin[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLatitudeDegMin
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO SELF
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= '0'
trans21:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans22
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans22
              ;  Precondition gps_storeCount == 0x03
              MOVLW    .3
              CPFSEQ   gps_storeCount, A
              GOTO     trans22
              ;  Command gpsLatitudeDegMin[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLatitudeDegMin
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0008
              MOVLW    HIGH(step_gps_State_0008)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0008)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans22:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0008 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0008:
              ;  Precondition gpsInput == '.'
trans23:      MOVLW    .46
              CPFSEQ   gpsInput, A
              GOTO     trans24
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsLatitudeHundredths := 0
              BANKSEL  gpsLatitudeHundredths
              CLRF     gpsLatitudeHundredths
              CLRF     (gpsLatitudeHundredths + .1)
              ;  Transition GOTO gps_State_0009
              MOVLW    HIGH(step_gps_State_0009)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0009)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans24:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0009 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0009:
              ;  Precondition gpsInput >= '0'
trans25:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans26
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans26
              ;  Precondition gps_storeCount <= 0x00
              MOVLW    .1
              CPFSLT   gps_storeCount, A
              GOTO     trans26
              ;  Command gpsLatitudeHundredths[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLatitudeHundredths
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO SELF
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= '0'
trans26:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans27
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans27
              ;  Precondition gps_storeCount == 0x01
              MOVLW    .1
              CPFSEQ   gps_storeCount, A
              GOTO     trans27
              ;  Command gpsLatitudeHundredths[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLatitudeHundredths
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0010
              MOVLW    HIGH(step_gps_State_0010)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0010)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans27:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0010 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0010:
              ;  Precondition gpsInput == '$'
trans28:      MOVLW    .36
              CPFSEQ   gpsInput, A
              GOTO     trans29
              ;  Transition GOTO (Shared) dollar
              GOTO     enter_dollar
              ; -- Start of transition --
              ;  Precondition gpsInput == ','
trans29:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans30
              ;  Transition GOTO gps_State_0011
              MOVLW    HIGH(step_gps_State_0011)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0011)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO SELF
trans30:      RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0011 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0011:
              ;  Precondition gpsInput == 'S'
trans31:      MOVLW    .83
              CPFSEQ   gpsInput, A
              GOTO     trans32
              ;  Command gpsFlags:1 := false
              BCF      gpsFlags, 1, A
              ;  Transition GOTO (Shared) gps_State_0012
              GOTO     enter_gps_State_0012
              ; -- Start of transition --
              ;  Precondition gpsInput == 'N'
trans32:      MOVLW    .78
              CPFSEQ   gpsInput, A
              GOTO     trans33
              ;  Command gpsFlags:1 := true
              BSF      gpsFlags, 1, A
              ;  Transition GOTO (Shared) gps_State_0012
              GOTO     enter_gps_State_0012
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans33:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0012 entry code.
;------------------------------------------------------------------------------
              ;  Transition GOTO gps_State_0012
enter_gps_State_0012: MOVLW    HIGH(step_gps_State_0012)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0012)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0012 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0012:
              ;  Precondition gpsInput == ','
trans34:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans35
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsLongitudeDegMin := 0
              BANKSEL  gpsLongitudeDegMin
              CLRF     gpsLongitudeDegMin
              CLRF     (gpsLongitudeDegMin + .1)
              CLRF     (gpsLongitudeDegMin + .2)
              CLRF     (gpsLongitudeDegMin + .3)
              CLRF     (gpsLongitudeDegMin + .4)
              ;  Transition GOTO gps_State_0013
              MOVLW    HIGH(step_gps_State_0013)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0013)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans35:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0013 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0013:
              ;  Precondition gpsInput >= '0'
trans36:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans37
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans37
              ;  Precondition gps_storeCount <= 0x03
              MOVLW    .4
              CPFSLT   gps_storeCount, A
              GOTO     trans37
              ;  Command gpsLongitudeDegMin[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLongitudeDegMin
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO SELF
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= '0'
trans37:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans38
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans38
              ;  Precondition gps_storeCount == 0x04
              MOVLW    .4
              CPFSEQ   gps_storeCount, A
              GOTO     trans38
              ;  Command gpsLongitudeDegMin[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLongitudeDegMin
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0014
              MOVLW    HIGH(step_gps_State_0014)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0014)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans38:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0014 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0014:
              ;  Precondition gpsInput == '.'
trans39:      MOVLW    .46
              CPFSEQ   gpsInput, A
              GOTO     trans40
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsLongitudeHundredths := 0
              BANKSEL  gpsLongitudeHundredths
              CLRF     gpsLongitudeHundredths
              CLRF     (gpsLongitudeHundredths + .1)
              ;  Transition GOTO gps_State_0015
              MOVLW    HIGH(step_gps_State_0015)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0015)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans40:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0015 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0015:
              ;  Precondition gpsInput >= '0'
trans41:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans42
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans42
              ;  Precondition gps_storeCount <= 0x00
              MOVLW    .1
              CPFSLT   gps_storeCount, A
              GOTO     trans42
              ;  Command gpsLongitudeHundredths[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLongitudeHundredths
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO SELF
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= '0'
trans42:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans43
              ;  Precondition gpsInput <= '9'
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans43
              ;  Precondition gps_storeCount == 0x01
              MOVLW    .1
              CPFSEQ   gps_storeCount, A
              GOTO     trans43
              ;  Command gpsLongitudeHundredths[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLongitudeHundredths
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0016
              MOVLW    HIGH(step_gps_State_0016)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0016)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans43:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0016 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0016:
              ;  Precondition gpsInput == '$'
trans44:      MOVLW    .36
              CPFSEQ   gpsInput, A
              GOTO     trans45
              ;  Transition GOTO (Shared) dollar
              GOTO     enter_dollar
              ; -- Start of transition --
              ;  Precondition gpsInput == ','
trans45:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans46
              ;  Transition GOTO gps_State_0017
              MOVLW    HIGH(step_gps_State_0017)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0017)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO SELF
trans46:      RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0017 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0017:
              ;  Precondition gpsInput == 'E'
trans47:      MOVLW    .69
              CPFSEQ   gpsInput, A
              GOTO     trans48
              ;  Command gpsFlags:2 := true
              BSF      gpsFlags, 2, A
              ;  Transition GOTO (Shared) gps_State_0018
              GOTO     enter_gps_State_0018
              ; -- Start of transition --
              ;  Precondition gpsInput == 'W'
trans48:      MOVLW    .87
              CPFSEQ   gpsInput, A
              GOTO     trans49
              ;  Command gpsFlags:2 := false
              BCF      gpsFlags, 2, A
              ;  Transition GOTO (Shared) gps_State_0018
              GOTO     enter_gps_State_0018
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans49:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0018 entry code.
;------------------------------------------------------------------------------
              ;  Transition GOTO gps_State_0018
enter_gps_State_0018: MOVLW    HIGH(step_gps_State_0018)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0018)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0018 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0018:
              ;  Precondition gpsInput == ','
trans50:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans51
              ;  Transition GOTO gps_State_0019
              MOVLW    HIGH(step_gps_State_0019)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(step_gps_State_0019)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO (Shared) root
trans51:      GOTO     enter_root

;------------------------------------------------------------------------------
; Node gps_State_0019 step code.
;------------------------------------------------------------------------------
              ; -- Start of transition --
step_gps_State_0019:
              ;  Command gpsQuality := gpsInput
trans52:      MOVFF    gpsInput, gpsQuality
              ;  Command gpsFlags:0 := true
              BSF      gpsFlags, 0, A
              ;  Transition GOTO (Shared) root
              GOTO     enter_root

              END
