/*****************************************************************************
 * This file was auto-generated by PICStateGenerator. Do not edit.
 * Generated: Mon Oct 31 21:42:49 GMT 2011
 *****************************************************************************/
#ifndef _GPS_H_
#define _GPS_H_

/*****************************************************************************
 * Initialisation method. Call before first use.
 *****************************************************************************/
extern void gpsInit(void);

/*****************************************************************************
 * Step method.
 * Call to advance state machine after setting input.
 *****************************************************************************/
extern void gpsStep(void);


/*****************************************************************************
 * Access Variables
 *****************************************************************************/
extern struct
{
unsigned FLAG_GPS_NEW_POSITION :1;
unsigned FLAG_GPS_NORTH :1;
unsigned FLAG_GPS_EAST :1;
} gpsFlags;
extern char gpsInput;


/*****************************************************************************
 * Variables for bank gpsBank1
 *****************************************************************************/
#pragma varlocate "gpsBank1" gpsLatitudeDegMin
extern char[] gpsLatitudeDegMin;
#pragma varlocate "gpsBank1" gpsLongitudeHundredths
extern char[] gpsLongitudeHundredths;
#pragma varlocate "gpsBank1" gpsTime
extern char[] gpsTime;
#pragma varlocate "gpsBank1" gpsLongitudeDegMin
extern char[] gpsLongitudeDegMin;
#pragma varlocate "gpsBank1" gpsQuality
extern char gpsQuality;
#pragma varlocate "gpsBank1" gpsLatitudeHundredths
extern char[] gpsLatitudeHundredths;

#endif
