;------------------------------------------------------------------------------
; This file was auto-generated by PICStateGenerator. Do not edit.
;------------------------------------------------------------------------------
              list     p=18F14K50
#include "p18f14k50.inc"

              GLOBAL   gpsInit
              GLOBAL   gpsStep
              GLOBAL   gpsLatitudeDegMin
              GLOBAL   gpsFlags
              GLOBAL   gpsLongitudeHundredths
              GLOBAL   gpsTime
              GLOBAL   gpsLongitudeDegMin
              GLOBAL   gpsQuality
              GLOBAL   gpsLatitudeHundredths
              GLOBAL   gpsInput

gpsAcs        UDATA_ACS
_statePtr              res .2
gpsFlags               res .1
gps_storeCount         res .1
gpsInput               res .1

              ; Please set up the linker to locate this block as required.
gpsBank1      UDATA
gpsLatitudeDegMin      res .4
gpsLongitudeHundredths   res .2
gpsTime                res .6
gpsLongitudeDegMin     res .5
gpsQuality             res .1
gpsLatitudeHundredths   res .2

gpsCode       CODE

;------------------------------------------------------------------------------
; State model initialisation.
;------------------------------------------------------------------------------
gpsInit:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; State model entry point.
; This method executes the code for the current state.
;------------------------------------------------------------------------------
gpsStep:      CLRF     PCLATU, A
              MOVFF    (_statePtr + .1), PCLATH
              MOVF     _statePtr, W, A
              MOVWF    PCL, A

;------------------------------------------------------------------------------
; Node root
;------------------------------------------------------------------------------
              ; -- Start of transition --
root:
              ;  Precondition gpsInput == 36
trans0:       MOVLW    .36
              CPFSEQ   gpsInput, A
              GOTO     trans1
              ;  Transition GOTO dollar
              MOVLW    HIGH(dollar)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(dollar)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans1:       MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node dollar
;------------------------------------------------------------------------------
              ; -- Start of transition --
dollar:
              ;  Precondition gpsInput == 71
trans2:       MOVLW    .71
              CPFSEQ   gpsInput, A
              GOTO     trans3
              ;  Transition GOTO gps_State_0000
              MOVLW    HIGH(gps_State_0000)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0000)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans3:       MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0000
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0000:
              ;  Precondition gpsInput == 80
trans4:       MOVLW    .80
              CPFSEQ   gpsInput, A
              GOTO     trans5
              ;  Transition GOTO gps_State_0001
              MOVLW    HIGH(gps_State_0001)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0001)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans5:       MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0001
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0001:
              ;  Precondition gpsInput == 71
trans6:       MOVLW    .71
              CPFSEQ   gpsInput, A
              GOTO     trans7
              ;  Transition GOTO gps_State_0002
              MOVLW    HIGH(gps_State_0002)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0002)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans7:       MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0002
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0002:
              ;  Precondition gpsInput == 71
trans8:       MOVLW    .71
              CPFSEQ   gpsInput, A
              GOTO     trans9
              ;  Transition GOTO gps_State_0003
              MOVLW    HIGH(gps_State_0003)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0003)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans9:       MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0003
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0003:
              ;  Precondition gpsInput == 65
trans10:      MOVLW    .65
              CPFSEQ   gpsInput, A
              GOTO     trans11
              ;  Precondition Flag gpsFlags:0 == false
              BTFSC    gpsFlags, 0, A
              GOTO     trans11
              ;  Transition GOTO gps_State_0004
              MOVLW    HIGH(gps_State_0004)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0004)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans11:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0004
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0004:
              ;  Precondition gpsInput == 44
trans12:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans13
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsTime := 0
              BANKSEL  gpsTime
              CLRF     gpsTime
              CLRF     (gpsTime + .1)
              CLRF     (gpsTime + .2)
              CLRF     (gpsTime + .3)
              CLRF     (gpsTime + .4)
              CLRF     (gpsTime + .5)
              ;  Transition GOTO gps_State_0005
              MOVLW    HIGH(gps_State_0005)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0005)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans13:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0005
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0005:
              ;  Precondition gpsInput >= 48
trans14:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans15
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans15
              ;  Precondition gps_storeCount <= 4
              MOVLW    .5
              CPFSLT   gps_storeCount, A
              GOTO     trans15
              ;  Command gpsTime[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsTime
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0005
              MOVLW    HIGH(gps_State_0005)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0005)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= 48
trans15:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans16
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans16
              ;  Precondition gps_storeCount == 5
              MOVLW    .5
              CPFSEQ   gps_storeCount, A
              GOTO     trans16
              ;  Command gpsTime[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsTime
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0006
              MOVLW    HIGH(gps_State_0006)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0006)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans16:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0006
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0006:
              ;  Precondition gpsInput == 36
trans17:      MOVLW    .36
              CPFSEQ   gpsInput, A
              GOTO     trans18
              ;  Transition GOTO dollar
              MOVLW    HIGH(dollar)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(dollar)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput == 44
trans18:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans19
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsLatitudeDegMin := 0
              BANKSEL  gpsLatitudeDegMin
              CLRF     gpsLatitudeDegMin
              CLRF     (gpsLatitudeDegMin + .1)
              CLRF     (gpsLatitudeDegMin + .2)
              CLRF     (gpsLatitudeDegMin + .3)
              ;  Transition GOTO gps_State_0007
              MOVLW    HIGH(gps_State_0007)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0007)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO gps_State_0006
trans19:      MOVLW    HIGH(gps_State_0006)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0006)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans20:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0007
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0007:
              ;  Precondition gpsInput >= 48
trans21:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans22
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans22
              ;  Precondition gps_storeCount <= 2
              MOVLW    .3
              CPFSLT   gps_storeCount, A
              GOTO     trans22
              ;  Command gpsLatitudeDegMin[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLatitudeDegMin
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0007
              MOVLW    HIGH(gps_State_0007)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0007)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= 48
trans22:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans23
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans23
              ;  Precondition gps_storeCount == 3
              MOVLW    .3
              CPFSEQ   gps_storeCount, A
              GOTO     trans23
              ;  Command gpsLatitudeDegMin[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLatitudeDegMin
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0008
              MOVLW    HIGH(gps_State_0008)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0008)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans23:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0008
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0008:
              ;  Precondition gpsInput == 46
trans24:      MOVLW    .46
              CPFSEQ   gpsInput, A
              GOTO     trans25
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsLatitudeHundredths := 0
              BANKSEL  gpsLatitudeHundredths
              CLRF     gpsLatitudeHundredths
              CLRF     (gpsLatitudeHundredths + .1)
              ;  Transition GOTO gps_State_0009
              MOVLW    HIGH(gps_State_0009)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0009)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans25:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0009
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0009:
              ;  Precondition gpsInput >= 48
trans26:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans27
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans27
              ;  Precondition gps_storeCount <= 0
              MOVLW    .1
              CPFSLT   gps_storeCount, A
              GOTO     trans27
              ;  Command gpsLatitudeHundredths[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLatitudeHundredths
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0009
              MOVLW    HIGH(gps_State_0009)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0009)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= 48
trans27:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans28
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans28
              ;  Precondition gps_storeCount == 1
              MOVLW    .1
              CPFSEQ   gps_storeCount, A
              GOTO     trans28
              ;  Command gpsLatitudeHundredths[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLatitudeHundredths
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0010
              MOVLW    HIGH(gps_State_0010)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0010)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans28:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0010
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0010:
              ;  Precondition gpsInput == 36
trans29:      MOVLW    .36
              CPFSEQ   gpsInput, A
              GOTO     trans30
              ;  Transition GOTO dollar
              MOVLW    HIGH(dollar)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(dollar)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput == 44
trans30:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans31
              ;  Transition GOTO gps_State_0011
              MOVLW    HIGH(gps_State_0011)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0011)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO gps_State_0010
trans31:      MOVLW    HIGH(gps_State_0010)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0010)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans32:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0011
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0011:
              ;  Precondition gpsInput == 83
trans33:      MOVLW    .83
              CPFSEQ   gpsInput, A
              GOTO     trans34
              ;  Command gpsFlags:1 := false
              BCF      gpsFlags, 1, A
              ;  Transition GOTO gps_State_0012
              MOVLW    HIGH(gps_State_0012)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0012)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput == 78
trans34:      MOVLW    .78
              CPFSEQ   gpsInput, A
              GOTO     trans35
              ;  Command gpsFlags:1 := true
              BSF      gpsFlags, 1, A
              ;  Transition GOTO gps_State_0012
              MOVLW    HIGH(gps_State_0012)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0012)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans35:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0012
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0012:
              ;  Precondition gpsInput == 44
trans36:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans37
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsLongitudeDegMin := 0
              BANKSEL  gpsLongitudeDegMin
              CLRF     gpsLongitudeDegMin
              CLRF     (gpsLongitudeDegMin + .1)
              CLRF     (gpsLongitudeDegMin + .2)
              CLRF     (gpsLongitudeDegMin + .3)
              CLRF     (gpsLongitudeDegMin + .4)
              ;  Transition GOTO gps_State_0013
              MOVLW    HIGH(gps_State_0013)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0013)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans37:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0013
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0013:
              ;  Precondition gpsInput >= 48
trans38:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans39
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans39
              ;  Precondition gps_storeCount <= 3
              MOVLW    .4
              CPFSLT   gps_storeCount, A
              GOTO     trans39
              ;  Command gpsLongitudeDegMin[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLongitudeDegMin
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0013
              MOVLW    HIGH(gps_State_0013)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0013)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= 48
trans39:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans40
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans40
              ;  Precondition gps_storeCount == 4
              MOVLW    .4
              CPFSEQ   gps_storeCount, A
              GOTO     trans40
              ;  Command gpsLongitudeDegMin[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLongitudeDegMin
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0014
              MOVLW    HIGH(gps_State_0014)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0014)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans40:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0014
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0014:
              ;  Precondition gpsInput == 46
trans41:      MOVLW    .46
              CPFSEQ   gpsInput, A
              GOTO     trans42
              ;  Command gps_storeCount := 0
              CLRF     gps_storeCount, A
              ;  Command gpsLongitudeHundredths := 0
              BANKSEL  gpsLongitudeHundredths
              CLRF     gpsLongitudeHundredths
              CLRF     (gpsLongitudeHundredths + .1)
              ;  Transition GOTO gps_State_0015
              MOVLW    HIGH(gps_State_0015)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0015)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans42:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0015
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0015:
              ;  Precondition gpsInput >= 48
trans43:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans44
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans44
              ;  Precondition gps_storeCount <= 0
              MOVLW    .1
              CPFSLT   gps_storeCount, A
              GOTO     trans44
              ;  Command gpsLongitudeHundredths[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLongitudeHundredths
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0015
              MOVLW    HIGH(gps_State_0015)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0015)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput >= 48
trans44:      MOVLW    .47
              CPFSGT   gpsInput, A
              GOTO     trans45
              ;  Precondition gpsInput <= 57
              MOVLW    .58
              CPFSLT   gpsInput, A
              GOTO     trans45
              ;  Precondition gps_storeCount == 1
              MOVLW    .1
              CPFSEQ   gps_storeCount, A
              GOTO     trans45
              ;  Command gpsLongitudeHundredths[gps_storeCount] := gpsInput
              LFSR     FSR0, gpsLongitudeHundredths
              MOVF     gps_storeCount, W, A
              MOVFF    gpsInput, PLUSW0
              ;  Command gps_storeCount++
              INCF     gps_storeCount, F, A
              ;  Transition GOTO gps_State_0016
              MOVLW    HIGH(gps_State_0016)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0016)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans45:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0016
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0016:
              ;  Precondition gpsInput == 36
trans46:      MOVLW    .36
              CPFSEQ   gpsInput, A
              GOTO     trans47
              ;  Transition GOTO dollar
              MOVLW    HIGH(dollar)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(dollar)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput == 44
trans47:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans48
              ;  Transition GOTO gps_State_0017
              MOVLW    HIGH(gps_State_0017)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0017)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO gps_State_0016
trans48:      MOVLW    HIGH(gps_State_0016)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0016)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans49:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0017
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0017:
              ;  Precondition gpsInput == 69
trans50:      MOVLW    .69
              CPFSEQ   gpsInput, A
              GOTO     trans51
              ;  Command gpsFlags:2 := true
              BSF      gpsFlags, 2, A
              ;  Transition GOTO gps_State_0018
              MOVLW    HIGH(gps_State_0018)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0018)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Precondition gpsInput == 87
trans51:      MOVLW    .87
              CPFSEQ   gpsInput, A
              GOTO     trans52
              ;  Command gpsFlags:2 := false
              BCF      gpsFlags, 2, A
              ;  Transition GOTO gps_State_0018
              MOVLW    HIGH(gps_State_0018)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0018)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans52:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0018
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0018:
              ;  Precondition gpsInput == 44
trans53:      MOVLW    .44
              CPFSEQ   gpsInput, A
              GOTO     trans54
              ;  Transition GOTO gps_State_0019
              MOVLW    HIGH(gps_State_0019)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(gps_State_0019)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans54:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0019
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0019:
              ;  Command gpsQuality := gpsInput
trans55:      MOVFF    gpsInput, gpsQuality
              ;  Command gpsFlags:0 := true
              BSF      gpsFlags, 0, A
              ;  Transition GOTO root
              MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   
              ; -- Start of transition --
              ;  Transition GOTO root
trans56:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

;------------------------------------------------------------------------------
; Node gps_State_0020
;------------------------------------------------------------------------------
              ; -- Start of transition --
gps_State_0020:
              ;  Transition GOTO root
trans57:      MOVLW    HIGH(root)
              MOVWF    (_statePtr + .1), A
              MOVLW    LOW(root)
              MOVWF    _statePtr, A
              RETURN   

              END
